pipeline {
  agent any
  stages {
    stage('help') {
      steps {
        echo 'test message'
        // sh 'npx playwright test --help'
      }
    }
    // stage('e2e-tests') {
    //   steps {
    //     sh '''#!/bin/bash
    //     npm ci
    //     npx playwright test
    //     '''
    //   }
    // }
  }
  // post {
  //   success {
  //     mail to: '2ktsklol@gmail.com',
  //          subject: "${currentBuild.currentResult}: Job ${env.JOB_NAME} (Build ${env.BUILD_NUMBER})",
  //          body: "УСПЕХ"
  //   }
  //   failure {
  //     mail to: '2ktsklol@gmail.com',
  //          subject: "${currentBuild.currentResult}: Job ${env.JOB_NAME} (Build ${env.BUILD_NUMBER})",
  //          body: "ПРОВАЛ"
  //   }
  //   always {
  //     cleanWs()
  //   }
  // }
}